package com.zt.model;

// Generated 2014-9-24 15:42:49 by Hibernate Tools 3.4.0.CR1

/**
 * BookStock generated by hbm2java
 */
public class BookStock implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2L;
	private String isbn;
	private Book book;
	private int stock;

	public BookStock() {
	}

	public BookStock(Book book, int stock) {
		this.book = book;
		this.stock = stock;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

}
