package com.zt.model;

// Generated 2014-9-24 15:42:49 by Hibernate Tools 3.4.0.CR1

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String isbn;
	private String bookName;
	private int price;
	private BookStock bookStock;

	public Book() {
	}

	public Book(String isbn, String bookName, int price) {
		this.isbn = isbn;
		this.bookName = bookName;
		this.price = price;
	}

	public Book(String isbn, String bookName, int price, BookStock bookStock) {
		this.isbn = isbn;
		this.bookName = bookName;
		this.price = price;
		this.bookStock = bookStock;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public BookStock getBookStock() {
		return this.bookStock;
	}

	public void setBookStock(BookStock bookStock) {
		this.bookStock = bookStock;
	}

}
